swagger: "2.0"
info:
  title: API Bot WhatsApp
  description: >
    Este projeto é um bot de automação do WhatsApp desenvolvido com Selenium WebDriver,
    permitindo interações automáticas com o WhatsApp Web como envio de mensagens,
    detecção de novas conversas, leitura de histórico, entre outros.
    Para contato profissional, acesse: https://www.linkedin.com/in/marco-antonio-aa3024233
  version: "1.0.0"
  contact:
    name: Marco Antonio da Silva Mesquita
    email: marcomesquitajr@hotmail.com

host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /start:
    post:
      summary: Inicia o bot
      description: >
        Inicia uma instância do bot em uma thread separada, abrindo a conexão com o WhatsApp Web.
        Se o bot já estiver rodando, retorna um erro informando que já está em execução.
      responses:
        200:
          description: Bot iniciado com sucesso.
          schema:
            type: object
            properties:
              status:
                type: string
              mensagem:
                type: string
        400:
          description: Bot já está em execução.

  /login:
    post:
      summary: Realiza o login do bot no WhatsApp Web
      description: >
        Verifica se o bot está logado no WhatsApp Web. 
        Se não estiver, gera um QRCode e fornece a URL da imagem para escaneamento.
        O QRCode é temporário e expira em 2 minutos.
      responses:
        200:
          description: Status do login retornado com sucesso.
          schema:
            type: object
            properties:
              status:
                type: string
                example: "aguardando_login"
              mensagem:
                type: string
                example: "Bot em execução aguardando leitura do QRCode."
              qrCodeUrl:
                type: string
                example: "http://localhost:3000/qrcode/abc123def456.png"
        400:
          description: Bot ainda não foi iniciado.
          schema:
            type: object
            properties:
              status:
                type: string
              mensagem:
                type: string
        500:
          description: Erro interno ao verificar ou gerar o QRCode.
          schema:
            type: object
            properties:
              status:
                type: string
              mensagem:
                type: string
              erro:
                type: string

  /status:
    get:
      summary: Verifica o status do bot
      description: >
        Retorna se o bot está rodando e se já está logado no WhatsApp Web.
      responses:
        200:
          description: Status retornado com sucesso.
          schema:
            type: object
            properties:
              status:
                type: string
              logado:
                type: boolean
              mensagem:
                type: string
        500:
          description: Erro ao verificar status.

  /send:
    post:
      summary: Envia uma ou mais mensagens para um contato
      description: >
        Pesquisa e abre a conversa com o contato informado, envia uma ou mais mensagens em sequência
        e retorna o histórico da conversa após o envio.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - contato
              - mensagens
            properties:
              contato:
                type: string
                example: "marco antonio"
              mensagens:
                type: array
                items:
                  type: string
                example:
                  - "Olá, tudo bem?"
                  - "Esta é a segunda mensagem."
                  - "Mensagem final do teste."
      responses:
        200:
          description: Mensagens enviadas com sucesso.
          schema:
            type: object
            properties:
              status:
                type: string
              mensagem:
                type: string
              dados:
                type: object
                properties:
                  historico_mensagens:
                    type: array
                    items:
                      type: string
        400:
          description: Dados inválidos ou bot inativo.
        500:
          description: Erro ao enviar mensagens.

  /history/{contato}:
    get:
      summary: Obtém histórico de mensagens com contato
      description: >
        Abre a conversa com o contato informado e retorna todas as mensagens disponíveis.
      parameters:
        - name: contato
          in: path
          required: true
          type: string
          description: Nome do contato para abrir a conversa e obter as mensagens.
      responses:
        200:
          description: Histórico obtido com sucesso.
          schema:
            type: object
            properties:
              status:
                type: string
              mensagem:
                type: string
              dados:
                type: object
                properties:
                  mensagens:
                    type: array
                    items:
                      type: string
        400:
          description: Bot não está ativo.
        500:
          description: Erro ao buscar histórico.

  /stop:
    post:
      summary: Finaliza o bot
      description: >
        Encerra o navegador e finaliza a execução do bot, liberando recursos.
      responses:
        200:
          description: Bot finalizado com sucesso.
          schema:
            type: object
            properties:
              status:
                type: string
              mensagem:
                type: string
